### ISSUE TITLE
rendering problem

### ISSUE THREAD

**Issue by nicokant** [MozillaItalia/mozillaitalia.github.old#2]
Problema di visualizzazione link
![screenshot-mozillaitalia github io 2015-09-11 15-15-43](https://cloud.githubusercontent.com/assets/6927678/9815669/1774494e-5898-11e5-8599-b7f54bd23d85.png)

**Comment by Mte90** [comment]
Si tratta di un problema di google font:
https://code.google.com/p/googlefontdirectory/issues/detail?id=368
https://github.com/google/fonts/issues/10

**Comment by nicokant** [comment]
ho risolto caricando manualmente il font fira sans
